FROM --platform=linux/amd64 golang:1.21.0-bullseye@sha256:0ed263861f71db3c4fed4d900b621aca03a3b91b8bc5f1dd56584af191c89d68
LABEL maintainer="Fleet Developers"

RUN apt-get update && apt-get install -y \
	gcc \
	libgtk-3-dev \
	libayatana-appindicator3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/fleet
RUN mkdir -p /output

WORKDIR /usr/src/fleet

COPY orbit ./orbit
COPY server ./server
COPY ee ./ee
COPY pkg ./pkg
COPY go.mod go.sum ./

CMD /bin/bash
